pref("extensions.{F382D07F-5CBE-49DA-7F3F-8F27F3AA51D6}.description", "chrome://timerfox/locale/timerfox.properties");
pref("extensions.timerfox.hour", 0);
pref("extensions.timerfox.minute", 0);
pref("extensions.timerfox.second", 0);
pref("extensions.timerfox.message", "The countdown is complete!");
pref("extensions.timerfox.customAudio", false);
pref("extensions.timerfox.audio", "");
pref("extensions.timerfox.install", false);
pref("extensions.timerfox.top", 320);
pref("extensions.timerfox.left", 240);
